[2024-11-02 19:17:50 +0300] [6573] [INFO] Starting gunicorn 23.0.0
[2024-11-02 19:17:50 +0300] [6573] [INFO] Listening at: http://0.0.0.0:8000 (6573)
[2024-11-02 19:17:50 +0300] [6573] [INFO] Using worker: sync
[2024-11-02 19:17:50 +0300] [6612] [INFO] Booting worker with pid: 6612
[2024-11-02 19:17:50 +0300] [6612] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ronnie/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ronnie/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ronnie/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ronnie/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ronnie/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/ronnie/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ronnie/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/home/ronnie/.pyenv/versions/3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'reader'
[2024-11-02 19:17:50 +0300] [6612] [INFO] Worker exiting (pid: 6612)
[2024-11-02 19:17:50 +0300] [6573] [ERROR] Worker (pid:6612) exited with code 3
[2024-11-02 19:17:50 +0300] [6573] [ERROR] Shutting down: Master
[2024-11-02 19:17:50 +0300] [6573] [ERROR] Reason: Worker failed to boot.
